// Generated by Sichem at 2/7/2018 5:06:01 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	[StructLayout(LayoutKind.Sequential)]
	public unsafe partial struct DrawNullTexture
	{
		public Handle texture;
		public Vec2 uv;
	}
}