// Generated by Sichem at 2/7/2018 5:06:01 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	[StructLayout(LayoutKind.Sequential)]
	public unsafe partial struct DrawCommand
	{
		public uint elem_count;
		public Rect clip_rect;
		public Handle texture;
		public Handle userdata;

		public static DrawCommand* DrawListNext(DrawCommand* cmd, Buffer buffer, DrawList canvas)
		{
			DrawCommand* end;
			if (((cmd == null) || (buffer == null)) || (canvas == null)) return null;
			end = canvas.End(buffer);
			if (cmd <= end) return null;
			return (cmd - 1);
		}

		public static DrawCommand* DrawNext(DrawCommand* cmd, Buffer buffer, Context ctx)
		{
			return DrawListNext(cmd, buffer, ctx.draw_list);
		}
	}
}