// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class Cursor
	{
		public Image img = new Image();
		public Vec2 size = new Vec2();
		public Vec2 offset = new Vec2();

	}
}
