// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackUserFontElement
	{
		public UserFont address;
		public UserFont old_value;

	}
}
