// Generated by Sichem at 2/7/2018 4:58:56 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackColor
	{
		public int head;
		public ConfigStackColorElement[] elements = new ConfigStackColorElement[32];
	}
}