// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackButtonBehavior
	{
		public int head;
		public ConfigStackButtonBehaviorElement[] elements = new ConfigStackButtonBehaviorElement[8];

	}
}
