// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackStyleItemElement
	{
		public StyleItem address;
		public StyleItem old_value = new StyleItem();

	}
}
