// Generated by Sichem at 2/7/2018 4:58:56 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackUserFontElement
	{
		public UserFont address;
		public UserFont old_value;
	}
}