// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackColor
	{
		public int head;
		public ConfigStackColorElement[] elements = new ConfigStackColorElement[32];

	}
}
