// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackStyleItem
	{
		public int head;
		public ConfigStackStyleItemElement[] elements = new ConfigStackStyleItemElement[16];

	}
}
