// Generated by Sichem at 2/7/2018 4:58:56 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackVec2
	{
		public int head;
		public ConfigStackVec2Element[] elements = new ConfigStackVec2Element[16];
	}
}