// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackVec2Element
	{
		public Vec2* address;
		public Vec2 old_value = new Vec2();

	}
}
