// Generated by Sichem at 2/7/2018 4:58:56 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class ConfigStackColorElement
	{
		public Color* address;
		public Color old_value = new Color();
	}
}