// Generated by Sichem at 2/7/2018 6:09:30 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	[StructLayout(LayoutKind.Sequential)]
	public unsafe partial struct Memory
	{
		public void* ptr;
		public ulong size;
	}
}