// Generated by Sichem at 2/6/2018 7:10:18 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class MenuState
	{
		public float x;
		public float y;
		public float w;
		public float h;
		public Scroll offset = new Scroll();

	}
}
