// Generated by Sichem at 2/7/2018 4:58:56 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class MenuState
	{
		public float x;
		public float y;
		public float w;
		public float h;
		public Scroll offset = new Scroll();
	}
}