// Generated by Sichem at 2/7/2018 6:17:24 PM

using System;
using System.Runtime.InteropServices;

namespace NuklearSharp
{
	public unsafe partial class StyleText
	{
		public Color color = new Color();
		public Vec2 padding = new Vec2();
	}
}